---
title: "P8123_final_project"
author: "Leyang Rui"
date: "2025-12-13"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(survey)
library(mice)
library(gtsummary)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# Load Data

```{r}
## Read csv that has filtered to only include blood pressure and hypertension sub-population
nhanes.df = read_csv("nhanes_bp.csv") |>
  ## select variables
  select(svy_id, svy_psu, svy_strata, svy_weight_mec, svy_year,
         demo_race, demo_gender, demo_age_years, bp_control_140_90, 
         bp_med_use, cc_smoke, cc_bmi, cc_diabetes, cc_ckd,
         cc_cvd_chd, cc_cvd_stroke, cc_cvd_hf) |>
  mutate(
    svy_year = factor(svy_year),
    demo_race = factor(demo_race),
    demo_gender = factor(demo_gender),
    bp_control_140_90 = as.numeric(factor(bp_control_140_90)) - 1,
    bp_med_use = factor(bp_med_use),
    cc_smoke = factor(cc_smoke),
    cc_bmi = factor(cc_bmi),
    cc_diabetes = factor(cc_diabetes),
    cc_ckd = factor(cc_ckd),
    cc_cvd_chd = factor(cc_cvd_chd),
    cc_cvd_stroke = factor(cc_cvd_stroke),
    cc_cvd_hf = factor(cc_cvd_hf)
  )
```

# Descriptive table

```{r}
nhanes.df |>
  tbl_summary(
    by = bp_control_140_90,
    include = c(
      demo_race, demo_gender, demo_age_years,
      bp_med_use, cc_smoke, cc_bmi,
      cc_diabetes, cc_ckd,
      cc_cvd_chd, cc_cvd_stroke, cc_cvd_hf
    ),
    missing = "ifany",
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    label = list(
      demo_race ~ "Race",
      demo_gender ~ "Sex",
      demo_age_years ~ "Age (years)",
      bp_med_use     ~ "Antihypertensive medication use",
      cc_smoke       ~ "Smoking status",
      cc_bmi         ~ "BMI category",
      cc_diabetes    ~ "Diabetes",
      cc_ckd         ~ "Chronic kidney disease",
      cc_cvd_chd     ~ "Coronary heart disease",
      cc_cvd_stroke  ~ "Stroke",
      cc_cvd_hf      ~ "Heart failure"
    )
  ) |>
  add_overall() |>
  bold_labels()
```


## RAO-SCOTT F-test Calculation


```{r}
nhanes.table = nhanes.df %>%
  mutate(wt_table = svy_weight_mec / 10)
  
des2 <- svydesign(
  ids = ~svy_psu,
  strata = ~svy_strata,
  weights = ~wt_table,
  nest = TRUE,
  data = nhanes.table
)

rs_test_gender <- svychisq(
  ~ bp_control_140_90 + demo_gender,
  design = des2,
  statistic = "F"
)

rs_test_race <- svychisq(
  ~ bp_control_140_90 + demo_race,
  design = des2,
  statistic = "F"
)

rs_test_age <- svychisq(
  ~ bp_control_140_90 + demo_age_years,
  design = des2,
  statistic = "F"
)

rs_test_bpmed <- svychisq(
  ~ bp_control_140_90 + bp_med_use,
  design = des2,
  statistic = "F"
)

rs_test_smoke <- svychisq(
  ~ bp_control_140_90 + cc_smoke,
  design = des2,
  statistic = "F"
)

rs_test_bmi <- svychisq(
  ~ bp_control_140_90 + cc_bmi,
  design = des2,
  statistic = "F"
)

rs_test_diabetes <- svychisq(
  ~ bp_control_140_90 + cc_diabetes,
  design = des2,
  statistic = "F"
)

rs_test_ckd <- svychisq(
  ~ bp_control_140_90 + cc_ckd,
  design = des2,
  statistic = "F"
)

rs_test_cvd_chd <- svychisq(
  ~ bp_control_140_90 + cc_cvd_chd,
  design = des2,
  statistic = "F"
)

rs_test_cvd_stroke <- svychisq(
  ~ bp_control_140_90 + cc_cvd_stroke,
  design = des2,
  statistic = "F"
)

rs_test_cvd_hf <- svychisq(
  ~ bp_control_140_90 + cc_cvd_hf,
  design = des2,
  statistic = "F"
)

rs_test_gender; rs_test_race; rs_test_age; rs_test_bpmed; rs_test_smoke; rs_test_bmi; 
rs_test_diabetes; rs_test_ckd; rs_test_cvd_chd; rs_test_cvd_stroke; rs_test_cvd_hf
```


## Distribution Plots

### Seperate dataset and define survey object

```{r}
nhanes.table = 
  nhanes.table %>% 
  mutate(
    period_grp = case_when(
      svy_year %in% c("1999-2000", "2001-2002", "2003-2004",
                      "2005-2006", "2007-2008", "2009-2010", "2011-2012") ~ "Pre-2013",
      svy_year %in% c("2013-2014", "2015-2016", "2017-2020") ~ "Post-2013"),
    period_grp = factor(period_grp),
    wt_adj = case_when(period_grp == "Pre-2013"  ~ svy_weight_mec / 7,
                       period_grp == "Post-2013" ~ svy_weight_mec / 3)
  )

des <- svydesign(
  ids = ~svy_psu,
  strata = ~svy_strata,
  weights = ~wt_adj,
  nest = TRUE,
  data = nhanes.table
)
```

### Continuous variable

```{r}
layout(matrix(1:2, nrow = 1))
svyhist(~demo_age_years, design = subset(des, period_grp == "Pre-2013"),
        main = "Pre-2013", xlab = "Age (years)", col = "SKYBLUE")
svyhist(~demo_age_years, design = subset(des, period_grp == "Post-2013"),
        main = "Post-2013", xlab = "Age (years)", col = "PINK")
layout(1)
```

### Categorical variables

```{r}
cat_vars <- c(
  "demo_race", "demo_gender", "bp_med_use", "cc_smoke", "cc_bmi",
  "cc_diabetes", "cc_ckd", "cc_cvd_chd", "cc_cvd_stroke", "cc_cvd_hf"
)

plot_df <- nhanes.table %>%
  select(period_grp, wt_adj, all_of(cat_vars)) %>%
  pivot_longer(
    cols = all_of(cat_vars),
    names_to = "variable",
    values_to = "category"
  ) %>%
  filter(!is.na(category)) %>%
  mutate(category = as.factor(category)) %>%
  group_by(period_grp, variable, category) %>%
  summarise(
    w = sum(wt_adj, na.rm = TRUE),
    .groups = "drop_last"
  ) %>%
  mutate(prop = w / sum(w)) %>%
  ungroup() %>%
  mutate(period_grp = factor(period_grp, levels = c("Pre-2013", "Post-2013")))

ggplot(plot_df,
       aes(x = prop, y = category, fill = period_grp)) +
  geom_col(width = 0.7) +
  facet_grid(variable ~ period_grp, scales = "free_y") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_fill_manual(
    values = c(
      "Pre-2013" = "#87CEEB",  
      "Post-2013" = "#FFC0CB"
    )
  ) +
  labs(
    x = "Weighted proportion",
    y = NULL,
    title = "Distribution of categorical variables before and after 2013"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "none",
    strip.text.y = element_text(angle = 0)
  )
```

# SRMI for missing data

```{r}
## set unnecessary variables to 0
pred = quickpred(nhanes.df, mincor = .1,  
                  exclude = c("svy_id", "svy_psu", "svy_strata", "svy_weight_mec", "svy_year"),
                  method = "pearson")
ini = mice(nhanes.df, pred = pred, m = 5, maxit = 5, print = FALSE, seed = 123)
nhanes_comp = complete(ini) 
```

# Separate dataset based on survey years

```{r}
nhanes_comp = nhanes_comp |>
  mutate(
    period_grp = case_when(svy_year %in% c("1999-2000", "2001-2002", "2003-2004",
                      "2005-2006", "2007-2008", "2009-2010", "2011-2012") ~ "Pre-2013",
      svy_year %in% c("2013-2014", "2015-2016", "2017-2020") ~ "Post-2013"),
    period_grp = factor(period_grp),
    wt_adj = case_when(period_grp == "Pre-2013"  ~ svy_weight_mec / 7,
                       period_grp == "Post-2013" ~ svy_weight_mec / 3),
    cc_smoke = relevel(cc_smoke, ref="Never")
    )

nhanes_pre2013 = nhanes_comp |>
  filter(period_grp == "Pre-2013")

nhanes_post2013 = nhanes_comp |>
  filter(period_grp == "Post-2013")
```

# Modeling 

## Pre-2013

```{r}
svy_pre2013 = svydesign(
  strata=~svy_strata, id=~svy_psu, weights=~wt_adj, data=nhanes_pre2013, nest=T)

glm_pre2013 = svyglm(bp_control_140_90 ~ demo_race + demo_gender + demo_age_years
                     + demo_age_years + bp_med_use + cc_smoke + cc_bmi
                     + cc_ckd + cc_cvd_chd + cc_cvd_hf, 
                     design = svy_pre2013, family = quasibinomial)
summary(glm_pre2013)
```

## Post-2013

```{r}
svy_post2013 = svydesign(
  strata=~svy_strata, id=~svy_psu, weights=~wt_adj, data=nhanes_post2013, nest=T)

glm_post2013 = svyglm(bp_control_140_90 ~ demo_race + demo_gender + demo_age_years
                     + demo_age_years + bp_med_use + cc_smoke + cc_bmi
                     + cc_ckd + cc_cvd_chd + cc_cvd_hf, 
                     design = svy_post2013, family = quasibinomial)
summary(glm_post2013)
```

# Subpopulation Analysis

## Pre-2013

```{r}
svyby(~bp_control_140_90, ~demo_gender, design = svy_pre2013, svymean)
svyby(~bp_control_140_90, ~demo_race, design = svy_pre2013, svymean)
svyby(~bp_control_140_90, ~cc_ckd, design = svy_pre2013, svymean)
svyby(~bp_control_140_90, ~cc_smoke, design = svy_pre2013, svymean)
svyby(~bp_control_140_90, ~cc_bmi, design = svy_pre2013, svymean)
```

## Post-2013

```{r}
svyby(~bp_control_140_90, ~demo_gender, design = svy_post2013, svymean)
svyby(~bp_control_140_90, ~demo_race, design = svy_post2013, svymean)
svyby(~bp_control_140_90, ~cc_ckd, design = svy_post2013, svymean)
svyby(~bp_control_140_90, ~cc_smoke, design = svy_post2013, svymean)
svyby(~bp_control_140_90, ~cc_bmi, design = svy_post2013, svymean)
```

# Modeling with interactions

## Pre-2013

```{r}
glm_pre2013_inter = svyglm(bp_control_140_90 ~ demo_race + demo_gender + demo_age_years
                     + demo_age_years + bp_med_use + cc_bmi + cc_smoke
                     + cc_ckd + cc_cvd_chd + cc_cvd_hf + demo_age_years*demo_gender 
                     + cc_bmi*bp_med_use,
                     design = svy_pre2013, family = quasibinomial)
summary(glm_pre2013_inter)

## Wald test
regTermTest(glm_pre2013_inter, ~ demo_age_years:demo_gender)
regTermTest(glm_pre2013_inter, ~ cc_bmi*bp_med_use)
```

## Post-2013

```{r}
glm_post2013_inter = svyglm(bp_control_140_90 ~ demo_race + demo_gender + demo_age_years
                     + demo_age_years + bp_med_use + cc_bmi + cc_smoke
                     + cc_ckd + cc_cvd_chd + cc_cvd_hf + demo_age_years*demo_gender 
                     + cc_bmi*bp_med_use,
                     design = svy_post2013, family = quasibinomial)
summary(glm_post2013_inter)

## Wald test
regTermTest(glm_post2013_inter, ~ demo_age_years:demo_gender)
regTermTest(glm_post2013_inter, ~ cc_bmi*bp_med_use)
```

# OR Table

## Pre-2013

```{r}
OR_table_pre = tidy(glm_pre2013_inter) |>
  mutate(
    OR = round(exp(estimate), 2),
    CI_low = exp(estimate - 1.96 * std.error),
    CI_high = exp(estimate + 1.96 * std.error),
    CI = paste0("(", round(CI_low, 3), ", ", round(CI_high, 3), ")"),
    p.value = round(p.value, 4)
  ) |>
  select(term, OR, CI, p.value)

knitr::kable(OR_table_pre)
```

## Post-2013

```{r}
OR_table_post = tidy(glm_post2013_inter) |>
  mutate(
    OR = round(exp(estimate), 2),
    CI_low = exp(estimate - 1.96 * std.error),
    CI_high = exp(estimate + 1.96 * std.error),
    CI = paste0("(", round(CI_low, 3), ", ", round(CI_high, 3), ")"),
    p.value = round(p.value, 4)
  ) |>
  select(term, OR, CI, p.value)

knitr::kable(OR_table_post)
```

## Combined

```{r}
OR_table_combined = bind_rows(
  OR_table_pre  %>% mutate(Period = "Pre-2013"),
  OR_table_post %>% mutate(Period = "Post-2013")
) %>%
  select(term, Period, OR, CI, p.value) %>% 
  arrange(term, factor(Period, levels = c("Pre-2013", "Post-2013"))) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = recode(term,
                       "demo_raceNon-Hispanic Asian" = "Race (Asian)",
                       "demo_raceNon-Hispanic Black" = "Race (Black)",
                       "demo_raceNon-Hispanic White" = "Race (White)",
                       "demo_raceOther" = "Race (Other)",
                       "demo_genderWomen" = "Gender (Women)",
                       "demo_age_years" = "Age",
                       "bp_med_useYes" = "BP medication use",
                       "cc_bmi25 to <30" = "BMI (25 to <30)",
                       "cc_bmi30 to <35" = "BMI (30 to <35)",
                       "cc_bmi35+" = "BMI (35+)",
                       "cc_smokeCurrent" = "Smoke (current)",
                       "cc_smokeFormer" = "Smoke (former)",
                       "cc_ckdYes" = "CKD",
                       "cc_cvd_chdYes" = "CHD",
                       "cc_cvd_hfYes" = "HF",
                       "demo_genderWomen:demo_age_years" = "Gender (Women) * Age",
                       "bp_med_useYes:cc_bmi25 to <30" = "BP medication * BMI (25 to <30)",
                       "bp_med_useYes:cc_bmi30 to <35" = "BP medication * BMI (30 to <35)",
                       "bp_med_useYes:cc_bmi35+" = "BP medication * BMI (35+)"
                       ))%>% 
  rename(Term = term, `p-value` = p.value) 

# Reorder the terms and recode p-value
OR_table_combined = 
  OR_table_combined %>%
  mutate(
    term_group = case_when(
      grepl("^Race", Term)   ~ 1,
      Term == "Gender (Women)"     ~ 2,
      Term == "Age"          ~ 3,
      Term == "BP medication use"  ~ 4,
      grepl("^BMI", Term)    ~ 5,
      grepl("^Smoke", Term)  ~ 6,
      Term == "CKD"          ~ 7,
      Term == "CHD"          ~ 8,
      Term == "HF"           ~ 9,
      Term == "Gender (Women) * Age"    ~ 10,
      grepl("^BP medication \\*", Term) ~ 11,
      TRUE                   ~ 99
    )
  ) %>%
  arrange(term_group, Term) %>%
  select(-term_group) %>% 
  group_by(Term) %>%
  mutate(Term = if_else(row_number() == 1, Term, "")) %>%  # collapse the identical term rows
  ungroup() %>% 
  mutate(
    `p-value` = ifelse(`p-value` < 0.0001, "< 0.0001", 
                       sprintf("%.4f", round(`p-value`, 4)))
    )

knitr::kable(OR_table_combined)
```








